Chatbot/urls.py
from django.urls import path, include
from . import views
app_name = "Chatbot"
urlpatterns = [
   path('', views.Init.as_view(), name="init"),
   path('register/', views.Register.as_view(), name='register'),
   path('login/', views.Login.as_view(), name='login'),
   
   path('home', views.home.as_view(), name="home")
]

Web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Chatbot.urls'))
]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Chatbot/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class ConversationMemory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    memory = models.TextField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    

class ChatMessage(models.Model):
    ROLE_CHOICES = (
        ("human", "Usuário"),
        ("ai", "Assistente"),
    )

    conversation = models.ForeignKey(ConversationMemory, on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]
        
    

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=450)
    price = models.FloatField()
    stock = models.IntegerField()
    created_at = models.DateTimeField(default=None, null=True)
    updated_at = models.DateTimeField(default=None, null=True)
    
    def __str__(self):
        return self.name
        

Chatbot/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=150, label='Usuário')
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(widget=forms.PasswordInput, label='Senha')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirme a senha')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Esse nome de usuário já está em uso.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Esse email já está cadastrado.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("As senhas não coincidem.")

        return cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, label='Usuário')
    password = forms.CharField(widget=forms.PasswordInput, label='Senha')

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError("Usuário ou senha incorretos.")
            self.user = user

        return cleaned_data

Chatbot/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages
from django.contrib.auth import  login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

import json


from . import chatbot_utils
from .forms import RegisterForm, LoginForm
from .models import ConversationMemory, ChatMessage
class Init(TemplateView):
    template_name = "pages/init.html"
    
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            return context
        
    def post(self, request):
        context = self.get_context_data()
        user_input = request.POST.get("user_input", "")
        context['inicio'] = True
                
        if user_input:
    
            #response = chatbot_utils.chatbot_generate_response(user_input)
            response = {}
            context['response'] = response
            context['user_input'] = user_input
            context['number'] = [1] * 15
            
        return render(request, self.template_name, context )
    def get(self, request):
        context = self.get_context_data()
        context['number'] = [1] * 15
        context['inicio'] = True
        return render(request, self.template_name, context )
    
    
    

class Register(TemplateView):
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            user.save()
            messages.success(request, 'Conta criada com sucesso! Faça login.')
            return redirect('Chatbot:login')
        else:
            return render(request, 'pages/registration/register.html', {'errors': form.errors})
    
    def get(self, request):
        return render(request, 'pages/registration/register.html')


class Login(TemplateView):
    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            login(request, form.user)  # Função nativa do Django para login
            return redirect('Chatbot:home')
        return render(request, 'pages/registration/login.html', {'form': form})

    def get(self, request):
        form = LoginForm()
    
        return render(request, 'pages/registration/login.html', {'form': form})
    

class home(TemplateView):
    template_name = "pages/home.html"
    

        
    def get(self, request):
        context = self.get_context_data()
        conversation_id = request.GET.get("conversation_id", '')
        if conversation_id:
            conversation = get_object_or_404(ConversationMemory, user=request.user.id, id=conversation_id)
            messages = ChatMessage.objects.filter(conversation=conversation).order_by('created_at')
        
            context['conversation'] = conversation

            context['messages'] = messages
        
        return render(request, self.template_name, context)

    def post(self, request):
        context = self.get_context_data()
        conversation_id = request.GET.get("conversation_id", 0)
        user_message = request.POST.get('user_message')
        
        if user_message:
            conversation, _ = ConversationMemory.objects.get_or_create(user=request.user, id=conversation_id)
            messages = ChatMessage.objects.filter(conversation=conversation.id).order_by('created_at')
            response = chatbot_utils.generate_response_with_summary(conversation, user_message)
            
            context['conversation'] = conversation
            context['messages'] = messages
        else:
            print("no bitches")
        return render(request, self.template_name, context)
        

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChatBot</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Azeret+Mono:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'global/css/style.css' %}"> 
</head>
<body>


    {% block body %}

    {% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</html>

templates/pages/init.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}
    {% include 'partials/header.html' %}
    <section>
        <div class=" w-100 d-block" style="min-height: 550px;position: relative">
            
            <img class="w-100" style="max-height: 700px;" src="{% static 'global/css/images/wickedbackground.png' %}" alt="">
           
            <div class="mt-5 " style="position: absolute; top:35%; left: 50%; transform: translate(-50%, -50%)">  
                <div class="w-100 h-100 d-flex align-items-center justify-content-center flex-column" style="min-height:300px">
                    <h4 class="display-4 text-white"><b><span class="text-custom-secondary fs-1"> < </span> <i class="bi bi-music-note-list me-2" style="font-size:50px"></i>MAESTRO<span class="text-custom-secondary fs-1"> > </span> </b><h4>
                    <p class="fs-3 text-white"> Seu parceiro na jornada musical! <p>
                
                    <form action="{% url 'Chatbot:init' %}" method="POST" id="demostrationFeature">
                        <div class="input-group mt-5">
                            {% csrf_token %}
                            <input type="text" name="user_input" class="form-control input-custom" value="{{user_input}}" placeholder="Peça dicas de instrumentos, tutoriais, partituras...">
                            <button class="btn btn-custom-primary" type="submit" >
                                <i class="bi bi-search text-white"></i>
                            </button>
                      
                        </div>  
                    </form>     
                    
                    
                </div>
                <div class="card w-100  bg-custom-blured card-custom-scale " style="height:250px; overflow-y: scroll;">
                    <div class="card-header font-primary"><b>Maestro:</b></div>
                    <div class="card-body font-primary">
                            <p>{{ response.practice_tip }}</p>
                            <p>{{ response.recommended_instrument }}</p>
                    </div>
                </div>
            </div>

        
        </div>
    </section>

    <section class="container-fluid">
        <h4 class="text-custom-primary ms-5"><i class="bi bi-music-player-fill"></i> Confira nosso Cat&aacute;logo: </h4>
        <div class="row w-100 px-5 gx-5">
            
            {% for x in number %}
       
            <div class="mt-4 col-12 col-md-4 col-lg-3 ">
                <div class="card card-custom shadow-sm border-0 card-custom-scale pointer">
                    <img class="border-rounded" style="overflow: hidden;" src="https://picsum.photos/300/300?random={{forloop.counter}}" alt="Guitarra Acústica" />
                    <div class="card-body ">
                        <div class="stars text-warning">
                        ★★★★☆ <small>(120 avaliações)</small>
                        </div>
                        <h5 class="card-title fw-bold mt-4">Guitarra Acústica</h5>
                        <p class="text-success fw-semibold">R$ 1.499,00</p>
                    </div>
                </div>
            </div>

            
            {% endfor %}
            
        </div>
    </section>
{% endblock %}
{% block script %}




{% endblock %}

templates/partials/header.html
<header>
  <nav class="navbar navbar-expand-lg bg-custom-primary navbar-dark py-1">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Chatbot:init' %}"><span class="text-custom-secondary fs-2">< <i class="bi bi-music-note-list fs-4"></i> <span class="fs-3">MAESTRO</span> ></span>   </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse mt-2" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Chatbot:init' %}">{% if inicio %}•{% endif %} In&iacute;cio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pagina2/">{% if sobre_nos %}•{% endif %} Sobre N&oacute;s</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pagina3/">{% if contato %}•{% endif %} Contato</a>
          </li>          
          <li class="nav-item">
            <a class="nav-link" href="/pagina3/">{% if catalogo %}•{% endif %} Catálogo</a>
          </li>
        </ul>
        
        <div class="d-flex">
          <a href="{% url 'Chatbot:login' %}" class="btn btn-outline-light me-2">Login</a>
          <a href="{% url 'Chatbot:register' %}" class="btn btn-light">Registro</a>
        </div>
      </div>
    </div>
  </nav>
</header>